[package]
name = "device-util"
version = "0.1.0"
description = "Utility crate for manually binding/unbinding ethernet devices to/from drivers"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]