[package]
name = "mangonel"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
mangonel-libxdp = { workspace = true }
mangonel-nic = { workspace = true }

axum = { workspace = true }
clap = { workspace = true }
core_affinity = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
