[package]
name = "mangonel"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
device-util.workspace = true
dpdk-sys.workspace = true