[package]
name = "mangonel"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
mangonel-libxdp = { workspace = true }

axum = { workspace = true }
core_affinity = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
