[package]
name = "mangonel-libxdp"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[dependencies]
mangonel-libxdp-sys = { workspace = true }
mangonel-nic = { workspace = true }

libc = { workspace = true }
rtrb = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
