[package]
name = "mangonel-libxdp-rs"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
libc = "0.2"
mangonel-libxdp-sys = { path = "../crates/libxdp-sys" }
