[package]
name = "dpdk-sys"
version = "23.11.0"
description = "Raw bindings to Intel DPDK library"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0"
pkg-config = "0.3.28"