#!/bin/bash

sudo ip netns add vlan
sudo ip netns exec vlan ip link set lo up

sudo ip link add veth0 type veth peer name eth0
sudo ip link set eth0 netns vlan

sudo ip address add 192.168.255.0/24 dev veth0
sudo ip netns exec vlan ip address add 192.168.255.1/24 dev eth0
sudo ip link set veth0 up
sudo ip netns exec vlan ip link set eth0 up
