[package]
name = "dpdk-rs"
version = "0.1.0"
description = "Safe wrapper for raw DPDK bindings"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
dpdk-sys = { workspace = true }